In [4]:
import numpy as np

In [5]:
import numpy as np

def max_pool_backward(d_out, input_matrix, pool_size, stride):
    """
    Description: 
    ------------
    - Backpropagation through max pooling layer for batch inputs. 
    - The pooling layers are square 
    - The batch of the input image is taken into consideration 



    Parameters:
    -----------
    - d_out (numpy.ndarray): Gradient of the loss w.r.t. the output of the max-pooling layer, 
                             shape (B, C, out_height, out_width).

                             
    - input_matrix (numpy.ndarray): max-pooling layer input during forward pass, shape is (B, C, H, W).
    - pool_size (int): square pooling window
    
    - stride (int): stride operation

    Returns:
    --------
    - d_input (numpy.ndarray): Gradient of the loss w.r.t. the input of the max-pooling layer, 
                               shape (batch, channel, height, width).
    """
    batch_size, channels, input_h, input_w = input_matrix.shape
    _, _, output_h, output_w = d_out.shape

    d_input = np.zeros_like(input_matrix) # initialize gradient wrt  input matrix
    
    for b in range(batch_size):  
        
        for c in range(channels):  
            
            for i in range(output_h):  
                
                for j in range(output_w):  
                    
                    start_h = i * stride
                    start_w = j * stride
                    
                    end_h = start_h + pool_size
                    end_w = start_w + pool_size

                    pooling_region = input_matrix[b, c, start_h:end_h, start_w:end_w]

                    max_val = np.max(pooling_region)

                    for m in range(pool_size):
                        
                        for n in range(pool_size):
                            
                            if pooling_region[m, n] == max_val:
                                
                                d_input[b, c, start_h + m, start_w + n] += d_out[b, c, i, j]
                                break  # exit once when the max value gradient is assigned - 

    return d_input


In [8]:
# Example inputs
input_matrix = np.array([[
    [[1, 3, 2, 1],
     [4, 6, 5, 2],
     [7, 8, 9, 4],
     [5, 3, 2, 6]]
]])
d_out = np.array([[
    [[1, 2],
     [3, 4]]
]])
pool_size = (2, 2)
stride = 2

# Perform backpropagation
d_input = max_pool_backward(d_out, input_matrix, pool_size, stride)
print("Gradient w.r.t. input:\n", d_input) 

Gradient w.r.t. input:
 [[[[0 0 0 0]
   [0 1 2 0]
   [0 3 4 0]
   [0 0 0 0]]]]


In [10]:
# For batch size 4 
# Input matrix for 4 batches, 1 channel, 4x4 dimensions
input_matrix = np.array([
    [[[1, 3, 2, 1],   # Batch 1
      [4, 6, 5, 2],
      [7, 8, 9, 4],
      [5, 3, 2, 6]]],

    [[[2, 4, 1, 3],   # Batch 2
      [3, 7, 5, 2],
      [1, 4, 8, 6],
      [9, 2, 1, 7]]],

    [[[1, 5, 3, 7],   # Batch 3
      [6, 9, 2, 8],
      [4, 3, 5, 6],
      [7, 2, 1, 9]]],

    [[[3, 1, 4, 2],   # Batch 4
      [6, 8, 5, 1],
      [7, 3, 2, 4],
      [5, 1, 6, 8]]]
])

# Gradient of the loss with respect to the output (d_out) for 4 batches, 1 channel, 2x2 dimensions
d_out = np.array([
    [[[1, 2],   # Batch 1
      [3, 4]]],

    [[[2, 1],   # Batch 2
      [3, 2]]],

    [[[4, 3],   # Batch 3
      [1, 5]]],

    [[[2, 3],   # Batch 4
      [4, 1]]]
])

# Pooling parameters
pool_size = (2, 2)
stride = 1

# Perform backpropagation
d_input = max_pool_backward(d_out, input_matrix, pool_size, stride)

# Output the result
print("Gradient w.r.t. input for batch size 4:\n", d_input)

Gradient w.r.t. input for batch size 4:
 [[[[ 0  0  0  0]
   [ 0  3  0  0]
   [ 0  3  4  0]
   [ 0  0  0  0]]]


 [[[ 0  0  0  0]
   [ 0  6  0  0]
   [ 0  0  2  0]
   [ 0  0  0  0]]]


 [[[ 0  0  0  0]
   [ 0 13  0  0]
   [ 0  0  0  0]
   [ 0  0  0  0]]]


 [[[ 0  0  0  0]
   [ 0 10  0  0]
   [ 0  0  0  0]
   [ 0  0  0  0]]]]
