In [2]:
from cnn import cnn
import numpy as np

In [3]:
input_size = 3
num_output = 2


num_kernels = 6
kernel_size = 3

# 6 3x3 kernels


stride = 1
padding = 0

height, width, channels = 6, 6, 3  # Small 4x4 image with 3 color channels
mock_image = np.random.randint(0, 256, (channels, height, width), dtype=np.uint8)

cnn_model = cnn(input_size, num_kernels, kernel_size)
output = cnn_model.convolve(mock_image, stride, padding)

kernels =  [[[[4.93022784e-01 8.55218514e-01 8.68926611e-02]
   [4.42208796e-01 2.29112226e-01 9.01030798e-01]
   [4.10952427e-01 1.05436588e-02 6.66512363e-01]]

  [[1.33398455e-01 2.64259978e-02 6.45424685e-01]
   [6.34711015e-01 6.78883356e-01 9.53670870e-01]
   [4.19390132e-01 5.43255589e-01 8.15453396e-02]]

  [[8.32578848e-01 7.32139289e-01 9.66122843e-02]
   [5.84418038e-01 8.39260684e-02 9.37828742e-01]
   [1.76011035e-01 8.14420118e-01 8.53216424e-01]]]


 [[[5.26547930e-01 3.56276322e-01 5.06444049e-01]
   [7.61981455e-01 7.64064732e-01 7.64980032e-01]
   [7.31520446e-01 5.39602211e-01 9.45755599e-01]]

  [[4.49969229e-01 7.60514389e-01 7.11406699e-01]
   [8.48267347e-01 7.83153530e-01 4.67351510e-01]
   [4.23784719e-01 7.53615567e-01 6.77209429e-01]]

  [[9.16448152e-01 5.92439684e-01 3.40308388e-01]
   [6.70807310e-01 8.43641321e-01 7.07580398e-01]
   [7.28092686e-01 1.84099011e-02 9.90686122e-01]]]


 [[[6.71624120e-01 3.74250437e-01 1.35288185e-01]
   [4.49401700e-01 4.99

In [4]:
print("output = ")

print(output)

output = 
[[[1432.25388806 1758.24750252 1734.46953068 1469.8799639 ]
  [1752.36304636 1559.27508007 1354.52002085 1598.86289262]
  [1648.28936415 1515.87829088 1344.48182825 1766.53886796]
  [1920.75268035 1565.53840501 1648.68616076 1805.8255043 ]]

 [[2045.2306459  2162.7284911  1993.79474889 2146.1325379 ]
  [2308.08683786 2205.32546298 1970.76507888 2018.17035142]
  [2508.29160881 2055.39132682 2002.54426921 2233.66981236]
  [2335.51424213 2122.83032316 2287.82471892 2142.63404257]]

 [[1433.60312632 1556.39414802 1474.72723188 1587.45129708]
  [1618.62323043 1421.34773558 1277.48625466 1655.9203672 ]
  [1568.68579629 1657.15784559 1354.41332211 1625.26785412]
  [1776.96293433 1534.76054907 1543.56668686 1524.97741179]]

 [[1830.05862115 1756.09215332 1672.12627157 1841.92301607]
  [1965.01791257 1919.9480589  1599.4619344  1732.96366156]
  [2003.19419918 1862.18895161 1752.79755974 1762.3533762 ]
  [1976.1685589  1873.08278708 1943.18863295 1816.89470333]]

 [[1556.97429097 1623.

In [ ]:
mock_image.shape, output.shape