In [9]:
from cnn import cnn
import numpy as np

In [10]:
input_size = 3  
num_output = 2



num_kernels = 6
kernel_size = 3 

# 6 3x3 kernels 


stride = 1  
padding = 0

height, width, channels = 6, 6, 3  # Small 4x4 image with 3 color channels
mock_image = np.random.randint(0, 256, (channels, height, width), dtype=np.uint8)

cnn_model = cnn(input_size, num_kernels, kernel_size)
output = cnn_model.convolve(mock_image, stride, padding)


kernels =  [[[[0.35720708 0.99109233 0.47172364]
   [0.75944916 0.08121585 0.17425794]
   [0.67580093 0.7701177  0.27331875]]

  [[0.25043432 0.82138404 0.32642223]
   [0.8363378  0.83729143 0.00989159]
   [0.46624126 0.92002003 0.13536096]]

  [[0.76361809 0.74606238 0.8059607 ]
   [0.37473623 0.85636924 0.88929773]
   [0.54845727 0.81882197 0.18132854]]]


 [[[0.72886891 0.75783346 0.47340601]
   [0.05787758 0.68303646 0.20281199]
   [0.76776856 0.15563476 0.6391583 ]]

  [[0.01907709 0.8524835  0.49496271]
   [0.29852631 0.88285618 0.51996744]
   [0.05874442 0.99521117 0.84561536]]

  [[0.13588911 0.16093872 0.16249409]
   [0.3191581  0.42641176 0.46681395]
   [0.79784805 0.49470036 0.97787496]]]


 [[[0.82884668 0.53051523 0.22362442]
   [0.69162245 0.73386975 0.81641368]
   [0.96005703 0.07720992 0.78016362]]

  [[0.88696915 0.24053974 0.20813042]
   [0.27229239 0.79564669 0.08220774]
   [0.65066298 0.65484259 0.33075377]]

  [[0.50555358 0.5941123  0.37320813]
   [0.54451432 0.06

In [11]:
print("output = ")

print(output)

output = 
[[[1732.41368793 1787.82293681 2054.44743108 2022.29301491]
  [1799.49857526 2069.49543513 2229.04087779 2186.37972404]
  [2077.61638637 2099.95951046 2097.86318863 1988.49819626]
  [2084.8625422  2398.37116406 2050.8824375  2057.90109438]]

 [[1349.17622638 1428.84281464 1664.07559553 1779.58526979]
  [1600.95203342 1781.67218799 1843.88090026 1993.66645325]
  [1762.46812958 2263.94396708 1748.20026655 1739.97162012]
  [2016.12430471 1815.90077308 1803.68813656 1386.24268002]]

 [[1482.86191137 1479.91271597 1770.02585935 1945.03725144]
  [2006.0400885  1877.25953786 2339.47512573 2012.10250852]
  [2014.77989717 2189.56797152 1804.19578172 1975.29401662]
  [2001.14492793 1948.44418196 2046.28744799 1740.53444641]]

 [[1457.92388241 1550.89179256 1818.38263338 1926.55813046]
  [1996.04342831 2086.97982393 2184.86513418 1997.44831372]
  [2174.49310463 2036.90118742 1838.60288763 1893.34855649]
  [2064.8330806  2056.45499057 2001.74223249 1942.55833807]]

 [[1340.10269125 1661.

In [12]:
mock_image.shape, output.shape

((3, 6, 6), (6, 4, 4))

### Padding Function 


In [13]:
def padding(image, pad):
    """
    Add zero-padding to each channel of a 3D umpy tensor. 

    Parameters: 
    ----------

    image : numpy.ndarray 

        A 3D numpy array of shape (C, H, W), where: 
        - C is the number  of channels (3 for RGB iamges) 
        - H is the height of the image
        - W is the width of the image 

    pad : int 
        The amount of zero-padding to add around the borders on each channels. 
        Padding ill be added symmetrically so that there is equal padding on all sides. 


    Returns: 
    --------

    numpy.ndarray 
        A 3D array with shape (C, H + 2* pad , W + 2 * pad) 
        
    """

    # There are three channels; each channel will have paddings added 

    

### Pooling Function

#### Below is implementation of Max Pooling Function. The logic is consistent for min and average pooling 

In [14]:
# test case for pooling functions 

conv_image = np.random.rand(28, 28) 
conv_image.shape

def MaxPool( conv_image , kernel_size , stride=1): 
    """
    Subsampling layer... 
    
    """
    # Get input dimensions 
    input_height , input_width = conv_image.shape

    # Get the output dimensions 
    output_height = (input_height - kernel_size) // stride+1 
    output_width = (input_width - kernel_size) // stride+1 

    # 1. Initialize an np 2-D array for pooling kernel 
    pooled_ = np.zeros(( output_height, output_width )) 
    
    #print(pooled_.shape) 
        
    # 2. Scan through the input image and get the max 
    
    for j in range(0, input_height - kernel_size + 1, stride):
        for i in range(0, input_width - kernel_size + 1, stride):
            
            # Define the current window
            window = conv_image[j:j + kernel_size, i:i + kernel_size]

            #print("--- window.shape :" , window.shape) 

            # Get the max value in the window
            max_value = np.max(window)

            # Map max value to the output matrix
            pooled_[j // stride, i // stride] = max_value

    return pooled_         


result = MaxPool(conv_image , kernel_size=3 , stride=1)

In [15]:
result

array([[0.97883697, 0.97883697, 0.97883697, 0.96946714, 0.93395239,
        0.94043235, 0.95174362, 0.98875147, 0.98875147, 0.98875147,
        0.9694049 , 0.9694049 , 0.9694049 , 0.95354751, 0.8980904 ,
        0.90057344, 0.90057344, 0.90057344, 0.81398809, 0.81398809,
        0.81398809, 0.92029226, 0.92029226, 0.92029226, 0.95975828,
        0.95975828],
       [0.97883697, 0.97883697, 0.97883697, 0.96946714, 0.85446883,
        0.85446883, 0.80190663, 0.98875147, 0.98875147, 0.98875147,
        0.98339684, 0.98339684, 0.8980904 , 0.8980904 , 0.8980904 ,
        0.71176455, 0.88501174, 0.88501174, 0.88501174, 0.81398809,
        0.95887167, 0.95887167, 0.95887167, 0.92029226, 0.95975828,
        0.95975828],
       [0.78094336, 0.96946714, 0.96946714, 0.96946714, 0.8258086 ,
        0.8258086 , 0.8258086 , 0.98202401, 0.98202401, 0.98339684,
        0.98339684, 0.98339684, 0.8980904 , 0.8980904 , 0.8980904 ,
        0.88292936, 0.88501174, 0.88501174, 0.88501174, 0.77796746,
      

In [16]:
conv_image

array([[8.73976229e-01, 5.67415623e-01, 1.22239632e-01, 9.05194307e-01,
        9.33952393e-01, 4.07630294e-01, 6.28586191e-01, 9.40432355e-01,
        9.51743621e-01, 5.53697298e-01, 1.69573968e-01, 3.44760121e-01,
        9.69404898e-01, 9.53547507e-01, 4.18922666e-01, 3.86190984e-01,
        2.23413394e-01, 9.00573436e-01, 2.42573732e-02, 2.81289219e-01,
        2.12174396e-01, 1.69394546e-01, 5.72749183e-01, 8.57562269e-01,
        6.64536940e-01, 8.42119400e-01, 9.15197264e-02, 3.66005897e-02],
       [8.06387343e-02, 9.69821617e-01, 9.78836970e-01, 8.76533518e-01,
        7.97438638e-01, 8.54468830e-01, 8.01906628e-01, 4.98806945e-01,
        8.70699685e-02, 9.88751465e-01, 7.67816426e-01, 6.95140540e-01,
        4.14680526e-01, 6.95616008e-01, 1.70828422e-01, 2.17561822e-01,
        9.85052730e-02, 4.97951049e-02, 7.34999124e-02, 4.12146293e-01,
        8.13988086e-01, 6.78033855e-01, 3.13505427e-01, 9.20292263e-01,
        8.80807905e-01, 2.04040760e-01, 9.59758285e-01, 7.41349

In [17]:
np.mean([ [1.0, 0.0], [0.0, 1.0]]) 


0.5