In [8]:
from cnn import cnn
import numpy as np

In [9]:
input_size = 3  
num_output = 2



num_kernels = 6
kernel_size = 3 

# 6 3x3 kernels 


stride = 1  
padding = 0

height, width, channels = 6, 6, 3  # Small 4x4 image with 3 color channels
mock_image = np.random.randint(0, 256, (channels, height, width), dtype=np.uint8)

cnn_model = cnn(input_size, num_kernels, kernel_size)
output = cnn_model.convolve(mock_image, stride, padding)


kernels =  [[[[7.50707317e-01 4.33439525e-01 8.46076872e-01]
   [2.89933294e-01 5.45736929e-01 5.21480594e-01]
   [9.18776669e-01 8.13514253e-01 8.12451390e-02]]

  [[6.58198246e-01 9.86319297e-02 4.81738294e-01]
   [5.34199869e-01 8.81059881e-01 3.46950607e-01]
   [5.11493592e-01 2.07390834e-01 2.04471856e-01]]

  [[7.63081615e-01 5.08678241e-01 2.81422771e-01]
   [6.31670981e-01 7.26643340e-01 6.21118241e-01]
   [8.43952834e-01 9.60165334e-01 1.80454463e-01]]]


 [[[8.95265787e-01 6.44109911e-01 5.85789100e-01]
   [9.61350706e-01 6.35958053e-01 9.60674371e-01]
   [1.66662482e-01 5.90835197e-01 7.98213200e-01]]

  [[8.86445784e-01 5.83569915e-01 9.47738538e-01]
   [8.70518069e-02 1.28518210e-01 8.28061922e-01]
   [8.35553336e-01 6.16397280e-02 6.91387725e-01]]

  [[4.34700627e-01 2.12392487e-01 7.65822617e-01]
   [2.66318194e-01 6.45573987e-01 3.81079984e-01]
   [9.64661553e-02 5.34185433e-01 1.14744926e-01]]]


 [[[9.76899750e-01 9.48636822e-01 1.92950429e-01]
   [5.29506374e-01 2.12

In [10]:
print("output = ")

print(output)

output = 
[[[2112.6661356  1848.69419429 1505.07549283 1579.77113902]
  [2251.78323378 1785.59245357 1711.48573479 1821.25747438]
  [1928.78165492 1880.80218084 1763.77239472 1735.52051233]
  [1563.02565805 1701.38659387 1811.97786274 1795.71972769]]

 [[1924.52667383 1732.79005251 1618.88160669 1518.74705498]
  [2046.91647288 1733.61839905 1576.50506995 1643.1643453 ]
  [2096.07788159 1776.62922112 1691.07331427 1958.66823505]
  [1931.24441887 1600.2964509  1737.69130237 1779.89793037]]

 [[1869.34130611 1739.8528312  1510.81177161 1869.89933086]
  [2038.17915953 1838.5232441  1634.36372148 1757.96137063]
  [2103.79191018 1730.63941876 1657.65293215 1844.68124406]
  [1956.16085835 1481.19784671 1904.85174669 1918.04810789]]

 [[2332.3833692  1911.97820453 1722.60547113 1776.95906912]
  [2431.67426658 1937.76694851 1837.91217968 1846.5593447 ]
  [2266.02927712 1899.35230639 1791.20213291 1945.93652366]
  [1558.28298281 1758.00311523 2058.27373432 1841.22581821]]

 [[2028.7266623  1536.

In [11]:
mock_image.shape, output.shape

((3, 6, 6), (6, 4, 4))

In [37]:
# test case for pooling functions 

conv_image = np.random.rand(28, 28) 
conv_image.shape

def MaxPool( conv_image , kernel_size , stride=1): 
    """
    Subsampling layer... 
    
    """

    # Get input dimensions 
    input_height , input_width = conv_image.shape

    # Get the output dimensions 
    output_height = (input_height - kernel_size) // stride+1 
    output_width = (input_width - kernel_size) // stride+1 

    # 1. Initialize an np 2-D array for pooling kernel 
    pooled_ = np.zeros(( output_height, output_width )) 
    
    #print(pooled_.shape) 
        
    # 2. Scan through the input image and get the max 
    
    for j in range(0, input_height - kernel_size + 1, stride):
        for i in range(0, input_width - kernel_size + 1, stride):
            
            # Define the current window
            window = conv_image[j:j + kernel_size, i:i + kernel_size]

            # Get the max value in the window
            max_value = np.max(window)

            # Map max value to the output matrix
            pooled_[j // stride, i // stride] = max_value

    return pooled_         


result = MaxPool(conv_image , kernel_size=3 , stride=1)

In [38]:
result.shape

(26, 26)