In [21]:
from cnn import cnn
import numpy as np
import os 

In [70]:
input_size = 3  
num_output = 2



num_kernels = 6
kernel_size = 3 

# 6 3x3 kernels 


stride = 1  
padding = 0

height, width, channels = 6, 6, 3  # Small 4x4 image with 3 color channels
mock_image = np.random.randint(0, 256, (channels, height, width), dtype=np.uint8)

cnn_model = cnn(input_size, num_kernels, kernel_size)
output = cnn_model.convolve(mock_image, stride, padding)

print("-------") 

kernels =  [[[[8.69250150e-02 6.33240775e-01 7.35904613e-01]
   [8.48128095e-01 1.22776890e-01 8.76444076e-01]
   [6.42925564e-01 7.03946135e-01 9.10624004e-01]]

  [[6.24761271e-01 3.35865857e-01 8.25107331e-01]
   [3.63059212e-01 3.42281108e-02 8.30654507e-01]
   [3.45192145e-01 7.73834523e-01 3.62757895e-01]]

  [[8.61068020e-01 2.19510525e-01 9.74547265e-01]
   [7.79758775e-01 1.14237926e-01 5.65776620e-01]
   [9.85367312e-01 4.71065453e-01 1.82107139e-01]]]


 [[[4.84778367e-01 5.12457656e-01 7.41686944e-01]
   [6.98845853e-01 4.02550044e-01 2.18023107e-01]
   [6.45054168e-01 4.21703935e-01 1.32276211e-01]]

  [[9.00572301e-01 6.91221858e-01 6.83183856e-01]
   [8.22583876e-01 5.29661679e-01 8.15054428e-01]
   [4.98090754e-01 6.71753999e-02 4.05248088e-01]]

  [[4.97464894e-01 7.20202582e-01 1.06578730e-01]
   [1.40018539e-01 2.63683803e-01 2.66498393e-01]
   [7.32184578e-01 2.50730661e-01 6.33098063e-01]]]


 [[[4.94273850e-01 5.73294378e-01 8.38106963e-01]
   [4.04381502e-01 7.70

AttributeError: 'cnn' object has no attribute 'num_input'

In [23]:
print("output = ")

print(output)

output = 
[[[2015.61946614 1850.94873572 2067.13714708 2052.87586368]
  [2065.40344258 2195.90046293 2074.23173095 1909.25912789]
  [1662.33641237 2048.46892546 1753.67259872 1954.21490775]
  [2033.68658135 2139.00972532 1721.24050606 1847.42152091]]

 [[1943.0537816  1853.61791239 1945.64693147 1716.7551705 ]
  [1796.11751203 1818.9616952  1901.08678154 1865.03425176]
  [1820.83642285 2027.5480717  1645.07024857 1542.15703801]
  [1904.69779951 1846.27862682 1552.17022833 1758.64972428]]

 [[1573.47235398 1654.73976858 1899.98378757 1708.00999091]
  [1743.88495248 1709.50324327 1547.41453535 1503.5713816 ]
  [1652.07660335 1785.75889848 1263.9437586  1250.64073635]
  [1688.07805334 1454.03555213 1158.9760231  1749.74736413]]

 [[1254.01439578 1414.82662513 1339.49188353 1214.45566426]
  [1504.5521568  1329.56713237 1253.31348648 1154.5615053 ]
  [1000.77132347 1349.51015947 1134.1994622  1052.84335661]
  [1486.85674856 1379.46972069 1015.69488642 1303.67640916]]

 [[1503.74666519 1711.

In [24]:
mock_image.shape, output.shape

((3, 6, 6), (6, 4, 4))

### Padding Function 


In [25]:
def padding(image, pad):
    """
    Add zero-padding to each channel of a 3D umpy tensor. 

    Parameters: 
    ----------

    image : numpy.ndarray 

        A 3D numpy array of shape (C, H, W), where: 
        - C is the number  of channels (3 for RGB iamges) 
        - H is the height of the image
        - W is the width of the image 

    pad : int 
        The amount of zero-padding to add around the borders on each channels. 
        Padding ill be added symmetrically so that there is equal padding on all sides. 


    Returns: 
    --------

    numpy.ndarray 
        A 3D array with shape (C, H + 2* pad , W + 2 * pad) 
        
    """

    # There are three channels; each channel will have paddings added 

    

### Pooling Function

#### Below is implementation of Max Pooling Function. The logic is consistent for min and average pooling 

In [26]:
# test case for pooling functions 

conv_image = np.random.rand(28, 28) 
conv_image.shape

def MaxPool( conv_image , kernel_size , stride=1): 
    """
    Subsampling layer... 
    
    """
    # Get input dimensions 
    input_height , input_width = conv_image.shape

    # Get the output dimensions 
    output_height = (input_height - kernel_size) // stride+1 
    output_width = (input_width - kernel_size) // stride+1 

    # 1. Initialize an np 2-D array for pooling kernel 
    pooled_ = np.zeros(( output_height, output_width )) 
    
    #print(pooled_.shape) 
        
    # 2. Scan through the input image and get the max 
    
    for j in range(0, input_height - kernel_size + 1, stride):
        for i in range(0, input_width - kernel_size + 1, stride):
            
            # Define the current window
            window = conv_image[j:j + kernel_size, i:i + kernel_size]

            #print("--- window.shape :" , window.shape) 

            # Get the max value in the window
            max_value = np.max(window)

            # Map max value to the output matrix
            pooled_[j // stride, i // stride] = max_value

    return pooled_         


result = MaxPool(conv_image , kernel_size=3 , stride=1)

In [27]:
result

array([[0.83357415, 0.83357415, 0.83357415, 0.83328894, 0.95842361,
        0.95842361, 0.95842361, 0.92947915, 0.92947915, 0.92775121,
        0.92775121, 0.90714543, 0.77734474, 0.77734474, 0.93800458,
        0.93800458, 0.98436981, 0.98436981, 0.98436981, 0.90408706,
        0.90408706, 0.90408706, 0.9957843 , 0.9957843 , 0.9957843 ,
        0.93237486],
       [0.83357415, 0.83357415, 0.83357415, 0.71423438, 0.95842361,
        0.95842361, 0.95842361, 0.94361969, 0.94361969, 0.94361969,
        0.92775121, 0.97626438, 0.97626438, 0.97626438, 0.93800458,
        0.93800458, 0.93800458, 0.81935267, 0.81935267, 0.90408706,
        0.90408706, 0.90408706, 0.9957843 , 0.9957843 , 0.9957843 ,
        0.98682477],
       [0.72097922, 0.72097922, 0.91086843, 0.91086843, 0.95842361,
        0.95842361, 0.95842361, 0.94361969, 0.94361969, 0.94361969,
        0.92775121, 0.97626438, 0.97626438, 0.97780641, 0.97780641,
        0.97780641, 0.79272034, 0.91430449, 0.91430449, 0.91430449,
      

In [28]:
conv_image

array([[0.67461736, 0.03824668, 0.3004368 , 0.40165059, 0.83328894,
        0.04860653, 0.50505147, 0.4133679 , 0.92947915, 0.69023985,
        0.47016833, 0.80519272, 0.48949302, 0.5351839 , 0.57226755,
        0.03556076, 0.3566749 , 0.70861479, 0.98436981, 0.38324433,
        0.10650208, 0.54532955, 0.60038181, 0.41350027, 0.44665808,
        0.60227249, 0.45796898, 0.72281142],
       [0.18842066, 0.55516653, 0.83357415, 0.45987326, 0.63828843,
        0.52754611, 0.08450816, 0.30681455, 0.10521719, 0.25848282,
        0.71215108, 0.90714543, 0.02959006, 0.03215378, 0.77734474,
        0.50670706, 0.93800458, 0.72526089, 0.12471272, 0.81935267,
        0.18581622, 0.52590893, 0.27589228, 0.8802691 , 0.9957843 ,
        0.77783976, 0.23010797, 0.83746158],
       [0.47701745, 0.69184098, 0.72097922, 0.66412802, 0.71423438,
        0.04316053, 0.95842361, 0.14244446, 0.47359593, 0.85466259,
        0.92775121, 0.1878279 , 0.15737733, 0.44436766, 0.45480213,
        0.28562467, 0.0485

In [29]:
np.mean([ [1.0, 0.0], [0.0, 1.0]]) 


0.5

### padding function 

In [71]:
def padding(image, pad):
    """
    Add zero-padding to each channel of a 3D umpy tensor. 

    Parameters: 
    ----------

    image : numpy.ndarray 

        A 3D numpy array of shape (C, H, W), where: 
        - C is the number  of channels (3 for RGB iamges) 
        - H is the height of the image
        - W is the width of the image 

    pad : int 
        The amount of zero-padding to add around the borders on each channels. 
        Padding ill be added symmetrically so that there is equal padding on all sides. 


    Returns: 
    --------

    numpy.ndarray 
        A 3D array with shape (C, H + 2* pad , W + 2 * pad) 
        
    """

    # There are three channels; each channel will have paddings added 

    C, H, W = image.shape 
    output_shape = (C, H + 2 * pad, W + 2 * pad)
    output = np.zeros(output_shape)

    #print(output.shape)
    
    for channel_index in range(C):
        output[channel_index] = np.pad(image[channel_index], 
                                       pad_width=((pad, pad), (pad, pad)), 
                                       mode='constant', constant_values=0)    
    return output


ones = np.ones((3, 3, 3))

padding(ones, 1) 

array([[[0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 0.],
        [0., 1., 1., 1., 0.],
        [0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 0.],
        [0., 1., 1., 1., 0.],
        [0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 0.],
        [0., 1., 1., 1., 0.],
        [0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0.]]])

In [30]:
import numpy as np

# Predicted probabilities (softmax output)
output = np.array([[0.1, 0.7, 0.2], 
                   [0.3, 0.4, 0.3]])

# One-hot encoded true labels
y_target = np.array([[0, 1, 0], 
                     [1, 0, 0]])

def cross_entropy(output, y_target):
    return -np.sum(np.log(output + 1e-9) * y_target, axis=1)

def compute_cost(output, y_target):
    return np.mean(cross_entropy(output, y_target))

loss = cross_entropy(output, y_target)
cost = compute_cost(output, y_target)

print("Cross-entropy losses per sample:", loss)
print("Average cost:", cost)


Cross-entropy losses per sample: [0.35667494 1.2039728 ]
Average cost: 0.7803238717513818


### Backpropagation : The aim is to write a unit function that will capture how to do backpropagation in CNN 

#### NOTE: To do backprop, I need to know the architecture of the network. For now, I assume it has two CNNs and then one flattened layer 

In [36]:
print( os.getcwd() ) 
print("---------------") 
print ( os.listdir() ) 
print("---------------")
print( os.listdir('test case'))  
print("---------------")

/Users/shahriar/Desktop/nn final/cnn
---------------
['.DS_Store', '__pycache__', 'download_data.ipynb', 'cnn.py', 'README.md', '.gitignore', '.ipynb_checkpoints', 'test case-20241203T174356Z-001.zip', 'data_visualization.ipynb', '.git', 'test case', 'pool.py', 'test.ipynb']
---------------
['deer.npy', 'batch_images.npy', 'batch_labels.npy']
---------------


In [38]:
# Read the 32 images and their labels 
data_path = os.path.join(os.getcwd(), "test case", "batch_images.npy") 
label_path = os.path.join(os.getcwd(), "test case" , "batch_labels.npy") 


data = np.load(data_path)
labels = np.load(label_path) 

In [45]:
data.shape # batch size, C, H, W  

(32, 3, 32, 32)

In [46]:
labels.shape # label 

(32,)

In [56]:
labels, type(labels)


(array([6, 9, 9, 4, 1, 1, 2, 7, 8, 3, 4, 7, 7, 2, 9, 9, 9, 3, 2, 6, 4, 3,
        6, 6, 2, 6, 3, 5, 4, 0, 0, 9]),
 numpy.ndarray)

In [61]:
from sklearn.preprocessing import OneHotEncoder 

ohe = OneHotEncoder(sparse_output = False)

labels_ohe  = ohe.fit_transform( labels.reshape(-1, 1) )

In [63]:
labels_ohe

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 

In [65]:
# Your one-hot encoded labels
encoded_labels = np.array([
    [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
    [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
    [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
    [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
    [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
    [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
    [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
    [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
    [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
    [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
    [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
    [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
    [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
    [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
    [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
    [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]
])

# Initialize probabilities
np.random.seed(42)  # For reproducibility
softmax_predictions = []

# Select indices for correct predictions
correct_indices = np.random.choice(range(len(encoded_labels)), size=6, replace=False)

for i, label in enumerate(encoded_labels):
    if i in correct_indices:
        # Correct prediction: highest probability for the true label
        probs = np.random.dirichlet(np.ones(10), size=1)[0] * 0.5  # Generate random probabilities
        true_label_index = np.argmax(label)
        probs[true_label_index] = 0.9  # Assign highest probability to the correct label
        probs /= probs.sum()  # Normalize to ensure sum equals 1
    else:
        # Incorrect prediction: random probabilities with no preference for the true label
        probs = np.random.dirichlet(np.ones(10), size=1)[0]  # Generate random probabilities
        probs /= probs.sum()  # Normalize to ensure sum equals 1
    softmax_predictions.append(probs)

softmax_predictions = np.array(softmax_predictions)


In [67]:
softmax_predictions.shape # These is randomly generated data for implementation purpose 

(32, 10)

In [ ]:
"""
I need : 

labels (got it) 
predictions (got it) 

cnn architecture (this we can get in MMP's implementation 

for now, assume there is 1 CNN layer 

"""


def backward(): # for 1 CNN layer 
        """
        Description: 
        -----------
        The backpropagation in CNN. By convention, the backward() function does not have any paramters in pytorch. 
        We will keep our implementation consistent with that of pytorch.
        

        Arguments: 
        ----------

        Returns: 
        --------

    
        # NOTE: Take into account of the kernel/filter AND the conv layer   
        
        
        dL_by_dF = Convolution(Input, Loss gradient dL_by_dO 
        dL_by_dX = Full Convolution(180 degree rotated filter F, Loss gradient dL_by_d0) 
        
        """

        # Q. What will be the shape of dL_by_d0 
        
    
        # Rotate the filer 
        filter_180 = None
        
        