In [1]:
from cnn import cnn
import numpy as np

In [2]:
input_size = 3  
num_output = 2
num_kernels = 6
kernel_size = 3
stride = 1  
padding = 0
height, width, channels = 6, 6, 3  # Small 4x4 image with 3 color channels
mock_image = np.random.randint(0, 256, (channels, height, width), dtype=np.uint8)

cnn_model = cnn(input_size, num_kernels, kernel_size)
output = cnn_model.convolve(mock_image, stride, padding)


kernels =  [[[[0.301452   0.39764033 0.89540109]
   [0.66873594 0.662064   0.09126499]
   [0.83572754 0.34003116 0.40604413]]

  [[0.89874358 0.90524787 0.61532187]
   [0.45922434 0.76039952 0.31821267]
   [0.46797975 0.23321997 0.92156484]]

  [[0.90450849 0.84420164 0.11709443]
   [0.5262933  0.05292424 0.4690739 ]
   [0.59495944 0.81704844 0.54406023]]]


 [[[0.26351387 0.38249986 0.26193623]
   [0.64428437 0.37468623 0.98842607]
   [0.66120304 0.25982502 0.50622138]]

  [[0.97774112 0.74270516 0.09629577]
   [0.38820458 0.89556455 0.83180161]
   [0.60593314 0.61975936 0.1867967 ]]

  [[0.65957513 0.13178757 0.95814066]
   [0.63428749 0.103581   0.16778785]
   [0.05731432 0.15218128 0.14442814]]]


 [[[0.58116981 0.55137816 0.59388045]
   [0.16025599 0.13912246 0.83128286]
   [0.84623717 0.25909833 0.4978526 ]]

  [[0.69882282 0.44412876 0.22991397]
   [0.59887176 0.35786899 0.37925429]
   [0.07895902 0.81053533 0.60278318]]

  [[0.1375321  0.87627602 0.25302296]
   [0.14051714 0.45

In [3]:
print("output = ")

print(output)

output = 
[[[2047.99502455 2229.14473771 2066.96474362 2040.99047971]
  [1869.49729343 1818.26147531 1835.12604528 1929.67104207]
  [1601.9560726  1807.61551299 1763.3818945  1862.25733421]
  [1343.26885699 1274.75468518 1564.9239059  1835.0343889 ]]

 [[1637.3652651  1903.11709536 1579.76466361 1599.29957667]
  [1742.05034316 1745.00971515 1689.87926306 1685.84579989]
  [1562.57333751 1497.08769091 1526.63325617 1573.20683726]
  [1054.63162821 1163.9817753  1471.11280939 1420.06169748]]

 [[1678.43779634 1824.6975086  1618.32988055 1682.61503836]
  [1704.46712074 1548.41424873 1318.01293827 1474.49473259]
  [1148.41241861 1513.72740433 1498.58200146 1702.93848844]
  [ 835.0613687  1184.80285951 1358.91017485 1423.8650146 ]]

 [[1932.63863402 2092.02250892 2074.95901184 1808.68877163]
  [1956.40975617 1719.01773883 1693.20020004 1803.63513696]
  [1604.65959967 1731.73369874 1859.16205633 2014.2819682 ]
  [1199.0264668  1239.54487158 1417.88414262 1787.06161605]]

 [[1664.17544411 1819.